spring.datasource.url=jdbc:mysql://localhost:3306/dispatch_engine_db
spring.datasource.username=root
spring.datasource.password=Igorcoutinho1*


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
google.maps.api-key=${GOOGLE_MAPS_API_KEY}
api.security.token.secret=minha_senha_super_secreta_123